# Copyright (c) 2021 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0

manifest:
  self:
    path: app

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos

  defaults:
    remote: zephyrproject-rtos

  projects:
    - name: zephyr
      revision: main
      import:
        name-allowlist:
          - hal_espressif
          - mbedtls
          - lvgl
          - fatfs
    - name: mcuboot
      revision: main
      path: bootloader/mcuboot
    - name: gc9a01-driver
      path: modules/drivers/gc9a01
      url: https://github.com/amrithvenkat12/gc9a01a_zephyr_driver.git
      revision: main
      
